### PR TITLE
Updates KinD packages to 0.5.1 🐛

### LINKED ISSUE #239: Create DockerMachine control-plane fails due to overlayfs issue
/kind bug

**What steps did you take and what happened:**
While creating DockerMachine, I came across the following error in the control-plane node of the cluster. The error occurs during the `kubeadm init` and can be traced down to the kubelet logs which attempt to create static pods for kubernetes components. 

```
Sep 02 15:49:39 my-cluster-controlplane-0 kubelet[459]: E0902 15:49:39.052418     459 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "kube-scheduler-my-cluster-controlplane-0_kube-system(7d5d3c0a6786e517a8973fa06754cb75)" failed: rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: failed to mount rootfs component &{overlay overlay [workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/61/work upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snap
shots/61/fs lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1/fs]}: invalid argument: unknown
```

**What did you expect to happen:**
Kubernetes control-plane components should be installed and running. 

**Anything else you would like to add:**
The error can be further traced down to KinD (overlayfs related) and has been addressed. We just need to use a more recent version of KinD. The error also appears to be specific to the underlying os/kernel. 

**Environment:**

- capdctl version: n/a
- capd-manager version: Built from master -- commit  5931c16142d32b1f9c0c5c236a512813f4949386
- Kubernetes version (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04 and kernel: 4.19.7-041907-generic

### PR DESCRIPTION
**Pull request by Arvinderpal**
**What this PR does / why we need it**:
Updates the KinD package dependency to 0.5.1 in go.mod

**Which issue(s) this PR fixes** 
Fixes #239

### CODE REVIEW

**Comment by chuckha** [comment]
@Arvinderpal please run `go mod tidy` and this lgtm

**Comment by Arvinderpal** [comment]
@chuckha done. 
It looks like `go mod tidy` also removed some `indirect` packages. Is that to be expected?

**Comment by chuckha** [comment]
yes it is!

/lgtm

**Pull request merged**
