### PR TITLE
:sparkles: Add tilt support

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

/assign @ncdc

### CODE REVIEW

**Comment by chuckha** [comment]
What is the reason for this change? I don't think we should be adding anything to this repo.

It is unmaintained and unused. New features are not something we want to support on this version of CAPD.

**Comment by chuckha** [comment]
Holding until we have a reason to merge this

**Comment by detiber** [comment]
@chuckha main reason was to add tilt support for the current stable release, similar to the PRs that were recently merged for CABPK and CAPA. The CAPI PR will also be merging soon: https://github.com/kubernetes-sigs/cluster-api/pull/1955.

**Comment by chuckha** [comment]
> @chuckha main reason was to add tilt support for the current stable release, similar to the PRs that were recently merged for CABPK and CAPA. The CAPI PR will also be merging soon: [kubernetes-sigs/cluster-api#1955](https://github.com/kubernetes-sigs/cluster-api/pull/1955).

we aren't actively developing stable releases.

I don't support this but I won't hold it if others want it.

/hold cancel

**Comment by ncdc** [comment]
I need to test some upgrade tool changes, so I wanted a working Tilt setup for CAPI 0.2.x (although I'm planning to test CAPA, not CAPD). Vince suggested adding Tilt support for CAPD. I don't feel strongly one way or another for this repo, though. There isn't really any harm to having it in here, though, is here?

**Comment by chuckha** [comment]
It kind of indicates this repo is used and maintained when in reality no one is planning on using this. But the work is already done so feel free to merge it

**Comment by vincepri** [comment]
Feel free to close

**Pull request closed without merging**
