### PR TITLE
Add myself as a maintainer

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**:
Add myself as a maintainer for OWNERS

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by chuckha** [comment]
this sounds good, tradition tells me to wait 1 week and then merge.

**Comment by detiber** [comment]
+1 from me

**Comment by chuckha** [comment]
@liztio I think you should get on this list too as you've been doing work on the v1alpha1/release-0.1 branch, what do you think?

**Comment by ncdc** [comment]
We'll need a separate PR for the `release-0.1` branch

**Pull request merged**
