### PR TITLE
hack: include scripts for golint, gofmt, spelling, shellcheck, etc.

### LINKED ISSUE #18: add boiler plate check written in go
the existing k8s boiler plate checks are written in python, for some reason.
a boiler plate check can be written in go (~50 LOC). basically any new, custom verify checks should be either bash or go and we should not depend on extra languages if possible.

should be added to verify-all.sh once #13 merges.
i should add this in kinder too, because we don't have it there yet.

/assign
/kind feature
/priority important-longterm

### PR DESCRIPTION
**Pull request by neolit123**
was #13, but i managed to corrupt the branch and the PR cannot be re-opened.
now also includes a commit for boilerplate checks.

WRT to presubmit PR verification:
xref #5
fixes #18

for kinder we have this that uses prow's pod-utils:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/kubeadm/kubeadm-presubmits.yaml

similar can be done for kubernetes-sigs/cluster-api-provider-docker/presubmits.yaml

/kind feature
/priority important-soon
/assign @chuckha

### CODE REVIEW

**Comment by neolit123** [comment]
> One question, where does this code come from? Is there a repo where you're pulling this from or is it copy-pasta tribal knowledge?

- kinder for the bash script, some based on kind previously.
- boilerplate written today.

**Comment by chuckha** [comment]
I wonder if there's some way we could share these across similar applications 🤔 oh well, out of scope for this issue.

/approve

Thank you so much for this work :pray:

**Comment by neolit123** [comment]
> I wonder if there's some way we could share these across similar applications thinking oh well, out of scope for this issue.

i though about that. instead of booking a standalone repo for we can technically have them hosted somewhere (e.g. under kubeadm) and a local, per-project script can wget them and run them on demand. 

problems are:
- that most of the scripts need customization as the repos have different demands.
- does not provide, non-air gaped, self contained local verification for developers.

**Pull request merged**
