### PR TITLE
✨ Add DockerMachine.Spec.CustomImage for customizing the container image the node runs

### PR DESCRIPTION
**Pull request by joonas**
**What this PR does / why we need it**:

This enables the customization of the container image that is used for running a given DockerMachine instance. This is useful in situations where you'd like to customize the node image in some way to better suit your needs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by chuckha** [comment]
/ok-to-test

looking very nice

**Comment by joonas** [comment]
I believe this is good to go, I've done a good bit of testing locally and things look good.

**Pull request merged**
